### ISSUE TITLE
Automatically sync saves (and states?) to Google Drive

### ISSUE THREAD

**Issue by rodrigoswz** [Swordfish90/Lemuroid#102]
I used Syncthing to sync my savegames with other devices, but now with Android 11 this is impossible due to the restriction of apps accessing `[Internal Storage]/Android/data`.

Allowing the user to choose another folder would also prevent data from being completely lost in case of accidental uninstallation of Lemuroid.

**Comment by Swordfish90** [comment]
I thought that distinction wasn't enforced for backup application. I'm expecting the syncthing team to be qualified for a whitelisting and request full access to the filesystem.

Managing this with Lemuroid, while doable, would probably have the same cost than implementing sync using the google drive api. A solution which I'd like more. What do you think?

**Comment by rodrigoswz** [comment]
> I thought that distinction wasn't enforced for backup application. I'm expecting the syncthing team to be qualified for a whitelisting and request full access to the filesystem.

The official Syncthing app works well (unlike Syncthing-Fork which I can't even grant permission to access all files), but unfortunately not even file managers can access Android/data...

[There are some ways to partially access it](https://www.reddit.com/r/Android/comments/j3zgmm/managing_files_in_the_androiddata_folder_on/), but it's not yet needed to sync Lemuroid folder :/


> Managing this with Lemuroid, while doable, would probably have the same cost than implementing sync using the google drive api. A solution which I'd like more. What do you think?
It would be amazing! The reason for using Syncthing with Lemuroid is basically because of the lack of a save feature in the cloud. Google Drive would solve the issue 100%. 😁

**Comment by Swordfish90** [comment]
Sounds like we have a plan.

**Comment by Swordfish90** [comment]
This comes with version 1.9.0. Enjoy :)

**Comment by rodrigoswz** [comment]
That's amazing Filippo, thank you so much!

If possible, add a toast/dialog stating that sync is being performed on Android TV devices

**Comment by Swordfish90** [comment]
@rodrigoswz Glad you're enjoying it.

Sadly notifications are discarded on Android TV. They are basically reserved to system and OEMs: https://designguidelines.withgoogle.com/android-tv/patterns/notifications.html

There might be some ways around that, but nothing really straightforward I guess.
