### ISSUE TITLE
Gradle fails to sync due to BaseExtension extension

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/Lemuroid#105]
I'm trying to build this project in Android Studio, but the gradle fails to sync with this error:

`Extension of type 'BaseExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, KotlinterExtension, ReportingExtension, CheckstyleExtension]`

After further inspection, it is referring to the base `base.gradle.kts` file, on line 77: `extensions.configure(BaseExtension::class.java)`.

What is the proper way to build this project?

**Comment by Swordfish90** [comment]
Hi @tytydraco . In theory it should work when opening it in Android Studio. The only "strange" thing about the project is the use of gradle kotlin dsl. Which version of Android Studio are you using? Are you using gradle wrapper and using the bundled jvm?

**Comment by tytydraco** [comment]
Hi @Swordfish90, thanks for the response :)

I'm using Android Studio 4.0.1. I use it daily for my own app dev, so I know that it's not due to a bad install. Additionally, I'm not sure what you mean by using the gradle wrapper / bundled jvm. I'm using JVM 1.6 (same error with 1.8 though), and simply doing a standard Gradle Sync on the whole project.

**Comment by tytydraco** [comment]
I've updated to Android Studio 4.0.2, same issue. I really want to build this project and contribute haha.

**Comment by tytydraco** [comment]
Hey! Fixed it in this PR: https://github.com/Swordfish90/Lemuroid/pull/106
