### ISSUE TITLE
All gameplay is sped up (FF is off) outside of menus since 1.7.0

### ISSUE THREAD

**Issue by SebastianBovell** [Swordfish90/Lemuroid#107]
Title says it all

**Comment by Swordfish90** [comment]
Hi @SebastianBovell . I've been able to reproduce the issue only with PSP games. Are you able to see it also with other systems?

**Comment by Swordfish90** [comment]
This has been fixed with some changes in the ppsspp core: https://github.com/Swordfish90/Lemuroid/pull/113 .
