### ISSUE TITLE
Genesis games play with incorrect aspect ratio

### ISSUE THREAD

**Issue by slackercube** [Swordfish90/Lemuroid#108]
Hi, thanks for making such a great project.

I have noticed that Genesis games appear to use the incorrect aspect ratio (the image appears to be too short).

Attached is a screenshot from Lemuroid and RetroArch, both with the same game loaded, both using the same core (genesis_plus_gx). The RetroArch screenshot shows the correct aspect ratio, while the Lemuroid screenshot shows a compressed image.

I have tested this on two android devices:
- Essential Phone, running Android 10
- Samsung Galaxy Tab A, running Android 6

On both devices, the same aspect ratio issue is seen.

Let me know if you need any more information. I am happy to run further tests and help out however you need.

RetroArch Screenshot:
![Screenshot_20201013-085209_RetroArch](https://user-images.githubusercontent.com/72770555/95797549-229ade00-0d33-11eb-808e-54c830a51c79.png)

Lemuroid Screenshot:
![Screenshot_20201013-085313_Lemuroid](https://user-images.githubusercontent.com/72770555/95797572-2f1f3680-0d33-11eb-8e93-dab9e5d88630.png)

**Comment by Swordfish90** [comment]
Hi @slackercube . You're definitely right. I've been able to reproduce the issue myself. I think something funny might be going on with non-squared pixels, but we should definitely investigate this.

**Comment by Swordfish90** [comment]
@slackercube I fixed the issue in https://github.com/Swordfish90/LibretroDroid/pull/32 . It will be available later today or tomorrow in beta and after a few days in production.

I'm closing it, but feel free to reopen if you're still experiencing some aspect ratio issues.
