### ISSUE TITLE
Xbox gamepad triggers not recognized

### ISSUE THREAD

**Issue by manu3008** [Swordfish90/Lemuroid#109]
The triggers on the xbox gamepass are non mappable, and are not recognized playing N64 games for example Zelda Ocarina of time.

**Comment by Swordfish90** [comment]
Hi @manu3008 . Thank you for reporting this. Are you able to use them with other systems such as PSX?

If you go to "Gamepad settings" do your triggers appear there?

**Comment by manu3008** [comment]
They aren't recognized from the main menu.![Screenshot_20201014-013824_21f12b1316663fbd369c35432dda51b0.jpg](https://user-images.githubusercontent.com/30480261/95927050-10b24d00-0dbe-11eb-945f-b0091b34e50b.jpg)

**Comment by manu3008** [comment]
There is no option to map the R2 and L2 triggers.

**Comment by Swordfish90** [comment]
Ok. Thank you. It's definitely something that we need to take a look at.

**Comment by Swordfish90** [comment]
I just merged #115 which adds support for linear triggers (which basically take a different route on Android). You'd still have no option to map them, but they should be working correctly now. It will land in beta today or tomorrow and after a few days in production.

Feel free to reopen the issue if you're still experiencing some issues.

**Comment by manu3008** [comment]
Hi @Swordfish90, with the last update the gamepad function broke. It recognizes it's connected but won't work on any game, none of the buttons.

Also the "enable gamepads" setting even when the xbox controller isn't connected doesn't let the on-screen buttons appear unless I turn it off.

**Comment by Swordfish90** [comment]
@manu3008 Do you see any other gamepad connected (in Gamepads bindings menu)? I'm starting to think that maybe the Xbox gamepad gets assigned to port 2 for some reasons.

**Comment by manu3008** [comment]
@Swordfish90 not really, just the new gf_input setting and then the xbox button settings, tried setting the gf_input to unassigned but nothing worked.

**Comment by Swordfish90** [comment]
Android gamepad management is really making me crazy. @manu3008 Can you send me an email at my address here on github (or the support email address on google play)? I can send you an apk which should fix your issue before publishing it on google play beta.

**Comment by manu3008** [comment]
Sure, just sent you an email. 👍🏻

**Comment by Swordfish90** [comment]
Ok. So hopefully this time we should have a proper fix :smile:.
