### ISSUE TITLE
[Request] Manual key binding by detecting buttons pressed

### ISSUE THREAD

**Issue by K1nfinity** [Swordfish90/Lemuroid#110]
Hello. Recently got aware of Lemuroid from r/emulationonandroid and I could not be more happier. Thank you!

The issue is, I bought myself a new controller for XCloud (8bitdo SN30 Pro for Android).

And even though it works as intended on Xcloud, notably the 'Retropad select' binding does nothing on Lemuroid, preventing me from things like inserting coins on fbneo for example.

That was when I found out that the key bindings for this controller were messed up like in the picture below.
![Screenshot_20201015-011102_GamePad Tester.jpg](https://user-images.githubusercontent.com/63835776/96017513-0d35c900-0e85-11eb-8f4f-187b5fa1dc8b.jpg)
This is when I pressed the SELECT(or 'view') button on my controller.
* Quick Edit - Not shown in the picture, but L2 is recognized instead of SELECT.

Retroarch supports manual button detection (e.g. 'press a button for SELECT'), but since I _really_ prefer Lemuroid it would be nice to have the same option for poor souls like myself who bought such a stubborn gamepad.

Thank you (Again) and I wish you all the best!

**Comment by Swordfish90** [comment]
Hi @K1nfinity . Correct me if I'm wrong but you should already be able to do so in "Gamepad settings". If when you press SELECT your device fires L2 you could remap Button L2 -> Retro SELECT.

At this point, it would be intereseting to know where L2 is mapped.

I agree that an auto-configure gamepad function would be nice.

**Comment by K1nfinity** [comment]
Hello @Swordfish90, Binding L2 to SELECT worked.
To think about it, I was so close to troubleshooting it myself, but there could be other users who would benefit from such option.

Also for the 'actual' L2 and R2 buttons, it's set to 'Axis 13+' for R2 and 'Axis 12+' for L2.
Gamepad Tester app (in original post) and therefore, Lemuroid does not recognize the buttons (when set to 'Android Gamepad' mode).

Appreciate your swift reply!

**Comment by Swordfish90** [comment]
Thanks @K1nfinity . I just merged some changes which should add support for linear triggers #115 , like the one you have on your controller. It'll be available today or tomorrow in the beta channel.

Feel free to reopen the issue if something is still not working with your controller.
