### ISSUE TITLE
How can I apply color pallet to game boy games?

### ISSUE THREAD

**Issue by RobertAguilera712** [Swordfish90/Lemuroid#116]
Hello, I really love this amazing project, but I don't know how to apply the color pallet in game boy and Game Boy Color games.
I changed it and nothing happens. I have tried every option and the color pallet still the same in Pokemon crystal. I want to change the color pallet because it is different compared with pizza boy emulator.
![Screenshot_20201019-115805](https://user-images.githubusercontent.com/73130045/96487750-c63c3080-1202-11eb-9652-3a5bc51a1ff1.png)
![Screenshot_20201019-115714](https://user-images.githubusercontent.com/73130045/96487757-c6d4c700-1202-11eb-8168-aa318ab5b1dc.png)

**Comment by Swordfish90** [comment]
Hi @RobertAguilera712 , the palette setting exposed by gambatte actually regulates non-color games. GBC games come with their own palettes. Maybe Pizzaboy has some shaders applied on top, or they are just using different color mapping.

**Comment by RobertAguilera712** [comment]
> Hi @RobertAguilera712 , the palette setting exposed by gambatte actually regulates non-color games. GBC games come with their own palettes. Maybe Pizzaboy has some shaders applied on top, or they are just using a different color mapping.

Thank you for your reply. I didn't know that the color pallet that Lemuroid shows was the original because I never have a Game Boy Color
