### ISSUE TITLE
Chromecast with Google TV: Can find roms on SD card via Hub

### ISSUE THREAD

**Issue by FlyOnTheWall43** [Swordfish90/Lemuroid#127]
I have a USB-C hub connected to my Chromecast with Google TV (CCGTV) with an SD card in it that had a handful of roms, but I can't get Lemuroid to recognize them. Storage permission has been granted.

**Comment by Swordfish90** [comment]
This was fixed with Lemuroid 1.8.0, your Chromecast should now be able to see your directories.
