### ISSUE TITLE
Impossible to launch a game without active internet connexion

### ISSUE THREAD

**Issue by Massedil** [Swordfish90/Lemuroid#145]
**Actual** 

I see "Downloading assets", then "Something went wrong with Lemuroid. Please file a bug on GitHub and tell me what happened."

The game is then not started.

It works fine if I'm connected to the internet.

**Expected**

The game can be launched without an active internet connexion.

**Version**

1.8.0 FDroid

**Comment by Swordfish90** [comment]
Hi @Massedil thank you for reporting this, I've just tried reproducing this issue but I've not been able to.

Are you able to reproduce it every time you play with a system or just the first time after an upgrade?

The first time you play with a system after an update Lemuroid has to download the core. After it's done it is cached for every subsequent use (until an upgrade).

**Comment by Massedil** [comment]
Hi ! 

It is exactly what you described : the app needs internet after an upgrade and not anymore after the first launch. Thanks ! 

Can't the asset be included in the apk to totally remove the internet permission ? Why is it needed to download assets from the internet ?

**Comment by ChildishGiant** [comment]
Probably for licensing reasons, is my guess.

**Comment by Swordfish90** [comment]
Ok, this is the expected behaviour.

The main reason for cores not being bundled is the sheer size of them. A fat apk with every architecture is around 300Mb, but the f-droid version is 10Mb. This is also helpful when not using every console included in Lemuroid.

The internet permission would still be required to fetch thumbnails.

**Comment by Commenter25** [comment]
Ran into this some time ago, nothing was very direct about this (especially the "Something went wrong with Lemuroid." error) and for a second I thought Lemuroid was for some reason online only. My first question when I saw "Downloading assets" was "what assets?", and it wasn't until looking here that I realized what it meant.

Also, I can't really test it, but I swear I had launched a game before but suddenly couldn't while I was out. Does Lemuroid stop you from launching a game if it knows there's an update but can't get it? I'd think it would just fall back to the previous version in that case.

Outside of just making this more obvious in descriptions and such, perhaps could there be a clearer way to check and download cores in the settings? That way I could skim a screen to see which cores are installed, which ones need updates, etc if I know I'm gonna be without internet. I'd imagine a list of all the systems and their status, like this but less markdown tabley more androidey:

| Systems    | Status             |
| -------------- | ------------------ |
| Atari 2600 | Uninstalled 🔴 |
| SNES        |        Ready 🟢 |
| GBA          |    Outdated 🟡 |

(want to clarify so i don't sound like i'm ragging on it, outside of this the app is great; can get it from fdroid which i prefer, good emulators, fair bit of options, not a ugly headache to interact with *coughcoughretroarchcoughcough*)
