### ISSUE TITLE
Corrupt game states screen

### ISSUE THREAD

**Issue by drcouzelis** [Swordfish90/Lemuroid#149]
When playing a game, I press the "gear" to open the game states screen. The game states screen is corrupted. Please see the attached screenshot.

The issue exists in version 1.8.0. I do not see the issue when reverting to version 1.7.1

I have witnessed the issue when running a common NES ROM or Game Boy ROM.

Please let me know if I can provide any further information. Thank you!

Phone: Motorola Moto G4 "athene"
OS: Android Oreo 8.1 with root

![Screenshot_20201217-214058](https://user-images.githubusercontent.com/184875/102701066-28280f00-4221-11eb-9742-827123edb0bb.png)

**Comment by Swordfish90** [comment]
Ouch, that's horrible. Thank you for reporting this. Are you able to reproduce it consistently or does it happen sporadically? Also, is the menu working (as you can click stuff and see the expected results), or is it broken also functionally?

**Comment by drcouzelis** [comment]
Yes, it consistently happens.

Uninstall / reinstall / clear data / clear cache does not affect the issue.

The app does not freeze. I can press the "back" button to return to the game. I attempted to poke around on the screen and it appears to be functional. I was able to get to what appears to be a save state screen by tapping in the upper right corner of the screen (please see the attached screenshot) before pressing the back button a couple times to return to the game.

![Screenshot_20201219-203006](https://user-images.githubusercontent.com/184875/102703157-574a7a80-4239-11eb-8810-1f4ba3315bd8.png)

**Comment by FrancescoCappio** [comment]
I have a similar problem. 
Phone: Xiaomi Mi 5
OS: Android 9 (LineageOS with microg). 
The problem appeared in last version (the menu worked well before). 
I think it is only a visual issue as buttons seems to work (I can save and load state correctly by touching the screen where buttons probably are). 

It's a playstation game
![photo_2020-12-21_09-50-00](https://user-images.githubusercontent.com/39024504/102757635-e9559e80-4371-11eb-8a3e-5a5e738257ba.jpg)
![photo_2020-12-21_09-49-57](https://user-images.githubusercontent.com/39024504/102757654-efe41600-4371-11eb-84f5-fee6cc025483.jpg)

**Comment by sembitvea** [comment]
Hello, same issue here with 1.8 on android pie :
![Uploading Screenshot_20201229-102617_Lemuroid.png…]()

**Comment by alex100306** [comment]
I have this issue. Moto e5

**Comment by Swordfish90** [comment]
I've been able to reproduce the issue with the emulator and I've just pushed a fix on the beta channel on Google Play (1.8.1). Would you mind giving that a go just to confirm that the issue has been fixed also on your side?

**Comment by alex100306** [comment]
Sure :)

**Comment by drcouzelis** [comment]
I can confirm that version 1.8.1 on the Play Store has a game states screen that I would expect to see. There is no visible graphical corruption, and the items in the menu are functional. 

Thank you! :)

**Comment by Swordfish90** [comment]
Thank you for reporting and testing this out. I just tagged 1.8.1 which contains the fix for it so we can now close the issue.
