### ISSUE TITLE
Black texture with Image Renderer on OpenGL ES2 devices

### ISSUE THREAD

**Issue by SpaceFrags** [Swordfish90/Lemuroid#152]
I'm trying to use the last version on my Android TV, but I cannot start a single game: I tried some SNES games and some PSX games and all the time it just goes into a black screen with the audio perfectly working and also the input, but nothing is showing and sometimes the game crash directly to the main menu. I tried on different Android TVs, one being a Mi TV with Android 9, the other a Mi Box Global with Android 8 on 4K TVs and also tried on a 1080p monitor. The problem persist all the time and do not know what it could be, but before was working perfectly.

**Comment by Swordfish90** [comment]
Hi, thank you for reporting this. Are you able to reproduce the issue with Lemuroid 1.7.1?

**Comment by SpaceFrags** [comment]
Just tried that by sideloading the 1.7.1 version and indeed that version works perfectly: tried some PSX and SNES games, all of them show everything. Also just a note, it dosen't seem like the L3+R3 ingame menu seem to works, I tried with the pad in "Android Mode" which is with the Bluethooth and also with the 2.4 GHz connection, which it is seen as a XInpunt device.

**Comment by Swordfish90** [comment]
Thank you for testing the old version. It makes triaging the issue a lot easier. I've just finished digging into the code and I most likely found the culprit, I'll be working on a fix in the next days.

**Comment by Swordfish90** [comment]
I just pushed a beta update on Google Play beta (1.8.1), do you think you can give it a go just to confirm that the issue is fixed also on your Mi TV?

**Comment by SpaceFrags** [comment]
If I start the Beta program on the Play store on my phone, does it also download the last beta on my Android TV? I'm not really sure, maybe sideloading it would be faster! Anyway I'm joining the beta program and I will tell you my results as fast as I can.

**Comment by Swordfish90** [comment]
@SpaceFrags Thank you for taking a look into this, glad it worked. I'm aware of the input issue, basically on some devices with some gamepads Android correctly report them as port 2. It's a separate issue and hopefully, we'll have a workaround in the next release.
