### ISSUE TITLE
PSX Roms Won't open 

### ISSUE THREAD

**Issue by Nick090598** [Swordfish90/Lemuroid#154]
I have a bios loaded and the roms go into a black screen and don't load

**Comment by Swordfish90** [comment]
Hi @Nick090598 . Can you provide a bit more info regarding this issue? Which device are you using, under which Android version? Is the issue reproducible with every psx game? Is it working with a previous Lemuroid version?

**Comment by Nick090598** [comment]
I'm using a note 20 ultra and I'm on android 11, it seems every psx rom doesn't work and I've used the older version and the beta and it still goes to a black screen 

I downloaded almost all Playstation bios files and it keeps going to a black screen

**Comment by Nick090598** [comment]
It seems rebooting the phone fixes it.
