### ISSUE TITLE
[Bug] Non-native mGBA save files not being recognized

### ISSUE THREAD

**Issue by anthonyajumelles** [Swordfish90/Lemuroid#156]
Sun's far I have only seen this happening with GBA, will see if it's an issue with other emulators as well.

I start Golden Sun from my phone and save a few minutes in.

From my PC, I can load RetroArch and use the mGBA core to continue the save file. I then save after a few more minutes of playing.

The issue is that, when I go back to Lemuroid, the save file isn't detected and the game acts as if I am starting fresh.

//

Lemuroid doesn't recognize mGBA save files from mGBA desktop (renamed to .SRM) nor from mGBA's RetroArch Android core.

//

Wasn't able to replicate this bug with SNES so it seems it's limited to mGBA. Super Mario RPG and FFVI detected the save file post saving in RetroArch Android and RetroArch Desktop.

I was able to see the issue present with Castlevania - Circle of the Moon as well.

**Comment by Swordfish90** [comment]
Hi @anthonyajumelles thank you for the report. Can you please attach the culprit srm file? I'd like to perform a few tests on it.

**Comment by anthonyajumelles** [comment]
Sorry @Swordfish90,

Unfortunately I upgraded to Android 11 (Syncthing can't sync Android/Data subdirectories) and wiped the saves (due to them not working post use on desktop).

I'll try to create one for you to gander at ASAP.

**Comment by nullbasis** [comment]
Same problem here, except that the .SAV file was created in MGBA on my desktop. Same issue, though, where Lemuroid isn't detecting it. [Here's the file](https://github.com/Swordfish90/Lemuroid/files/5816358/Final_Fantasy_VI_Advance_sav.zip), if it would be helpful.

**Comment by Swordfish90** [comment]
Thank you @nullbasis . I was indeed able to replicate the issue on Final Fantasy VI. It looks like the mGBA core can create saves which are smaller than the exposed SRAM size, and Lemuroid was simply discarding them. The fix is ready and will be included in 1.9.0.

**Comment by DuendeInexistente** [comment]
Hey, coming from the future, having the same issue now. It's a save for the latest version of the Pokemon Unbound romhack, mgba 1.10.2 and lemuroid 1.16.0. Lemuroid seems to be discarding the save offhand when it sees it.
[04 14 doecomic.zip](https://github.com/user-attachments/files/17220142/04.14.doecomic.zip)
