### ISSUE TITLE
Multi-disk psx games/and in game saves deleting upon app closure

### ISSUE THREAD

**Issue by alex100306** [Swordfish90/Lemuroid#163]
I absolutely love this emulator. I recently switched from ios to android, and I was really missing delta. Then I found this. I am really enjoying it but there are two issues I have found. 

1. When playing psx games there is no inherent "switch disk" feature. I am not very good at messing with files, so I wouldn't know how to make it work without this feature.

2. In all systems I have tested ( nes, gba, gbc, psx) the saves are deleted (or just don't work) after exiting the app. When I'm in the app I can go in and out of a game and the saves work, but if I close the app and reopen it. The save is gone and I'm back to the beginning. Save states are good and all, but I'd prefer to be able to use in-game saves. 

Edit-sorry I take that back saves do not delete on psx just everything else I mentioned.

**Comment by alex100306** [comment]
No

**Comment by Swordfish90** [comment]
Hi, I'll try to answer both questions:

1. Multidisk games are supported, but they need to come as a pbp file or you can create an m3u file listing all disks. Here you can find how to do so:  https://docs.libretro.com/library/beetle_psx/#multiple-disk-games
2. How are you closing Lemuroid? Saves and states are persisted only when pressing quit or the back button. If you press your home button and kill Lemuroid (or ignore it and Android decides to kill it later) your saves will be gone.

If 2 is not the scenario, then please file a bug with all the info related to your device, android version etc.

**Comment by alex100306** [comment]
Is it possible to do either of these directly on android. I do not have access to a pc.
