### ISSUE TITLE
In-game saves sometimes don't persist after quitting game

### ISSUE THREAD

**Issue by nullbasis** [Swordfish90/Lemuroid#170]
I'm using Android 10, and version 1.8.1 of the app. So far I've gotten this to happen pretty consistently with Final Fantasy V Advance for GBA; I started the game in Lemuroid and saved it in Lemuroid, and after quitting the game from the settings menu and/or closing the app, the in-game save no longer remains. Save states are unaffected; they *do* remain after closing the app.

I've also tried this with Pokemon Fire Red (GBA) and the in-game save *does* remain after quitting the game and/or closing the app.

**Comment by anthonyajumelles** [comment]
The issue that was causing this seems to have been resolved in the 1.9.0 update. Go ahead and join the beta on Lemuroid's Google Play Store page to get access.

**Comment by nullbasis** [comment]
Ah. I prefer to avoid the Play Store where I can, so in the meantime I'll just keep on using savestates. Thanks for the response, though.
