### ISSUE TITLE
[Android TV] Gamepad bindings are not working at all

### ISSUE THREAD

**Issue by kreaninw** [Swordfish90/Lemuroid#171]
**Device:** 
- Xiaomi Mi Box S / Mi Box 4
- Ipega PG-9118

**Android version:**
- Android TV 9, kernel 4.9.113

**Lemuroid version:**
1.8.1

**Issue:**
The gamepad bindings are not working at all while playing games. The games I tried are on Sega Genesis, NES, and SNES, none of them responded to my gamepad. I can use my gamepad to control the UI of the app though.

My gamepad should work fine as I also play arcade games with this box using this gamepad on MAME4droid (0.139u1) without any issue. The difference is that I can **_map_** my gamepad buttons directly into the emulator instead of just picking the available preset options, which none of them are working.

I am not sure if this relates to issue #126 since the OP reported that the binding is not working correctly but in my case, it's not working at all. Moreover, in that case(on Android TV), the binding is working with SNES games, but not on N64 and PSX games.

**Comment by Swordfish90** [comment]
Hi @kreaninw . Is it possible that your gamepad has been detected on port 2? If you look into the bindings page do you see only one controller? I fixed a similar bug in 1.9.0-beta1, basically a ghost controller "virtual-search" was taking the first port.

**Comment by kreaninw** [comment]
> Hi @kreaninw . Is it possible that your gamepad has been detected on port 2? If you look into the bindings page do you see only one controller? I fixed a similar bug in 1.9.0-beta1, basically a ghost controller "virtual-search" was taking the first port.

Yes, I think this could be the issue. I see the "virtual-search" shows up in the gamepad bindings too as shown in the screenshot below:

![Screenshot_20210121-213006](https://user-images.githubusercontent.com/1403194/105429736-bfbdba80-5c30-11eb-9a33-709b2f9c8019.png)

**Comment by Swordfish90** [comment]
Ok, then it's a duplicate. You'll find the fixed version on the beta channel or you can wait a few days until I'll promote it to production.
