### ISSUE TITLE
Request: optimize the ds

### ISSUE THREAD

**Issue by lucariokalos** [Swordfish90/Lemuroid#190]
I tried on gba,The game is very smooth,when I tried on ds,the game is very lag.

**Comment by Meptt** [comment]
@lucariokalos Try to  change ds core in settings

**Comment by shabbirmahmud** [comment]
I change the core DeSmuMe to MelonDs.The game is running very smooth for me.DeSmuMe core is very laggy for me and the sound is also not good.

**Comment by Swordfish90** [comment]
Hi @lucariokalos , DS emulation is heavier compared to GBA emulation, so that's kinda of expected. Which Android device are you running? Have you tried changing core as @Meptt correctly suggested? Did that help?

**Comment by lucariokalos** [comment]
I am using  Samsung galaxy tab A(2015) .In other emulator, like Drastic,my game experience is so very smooth, and I did'nt experience any lag.

**Comment by dimaspaf14** [comment]
> I am using Samsung galaxy tab A(2015) .In other emulator, like Drastic,my game experience is so very smooth, and I did'nt experience any lag.

Same, i had drastic before but when i try this app its very lag, i tried to change core but its just same, please fix this...

I play on vivo y53
Os android 6.0.1
Snapdragon 425 @1.4ghz
2gb ram

i used to play pubg mobile thats heavier than this but it can run smoothly
