### ISSUE TITLE
Unable to run PSX roms A11 see attached video

### ISSUE THREAD

**Issue by HJMBgit84** [Swordfish90/Lemuroid#196]
Hi Dev, please take a look on the attached video that shows unable to run psx roms for poco f2 pro.

Thanks for your work

**Comment by Swordfish90** [comment]
Hi, @HJMBgit84 . I don't see any attached video. If you're having issues with PSX detected but not loading, it's either you're missing a valid PSX BIOS file or a file copy failed. Please try putting a valid BIOS file in your ROMs directory and clear the application cache.
