### ISSUE TITLE
Lemuroid Build with LegacyStorage?

### ISSUE THREAD

**Issue by mo123** [Swordfish90/Lemuroid#198]
Please build an app with Legacy Storage so storage can work correctly on Android 10 TV devices.
Or the target api can be changed to Android 9.

Add to AndroidManifest.xml
        android:requestLegacyExternalStorage="true"

Unfortunately I get the following errors when building Lemuroid
https://0bin.net/paste/dzAaVkij#Ez9-w+p62xbWzFkXhEYNs41nocghAYFegwmo2nj8XZs

**Comment by Swordfish90** [comment]
Hi. Lemuroid already includes that flag to make it work on Android 10 TV devices. Which version have you been testing?
