### ISSUE TITLE
Allow turning off specific connected gamepads

### ISSUE THREAD

**Issue by lukittoys** [Swordfish90/Lemuroid#215]
Good Morning!

 i have a tlcp715 tv and downloaded the lemuroid. it recognizes the usb games and the joystick, but when I enter the game and stop recognizing the joystick, ask to press l3 + r3 to configure, I press and nothing happens. can you help me?

**Comment by dan082** [comment]
I have the same issue. It seems that the joystick (mine is a Pega 9076) is detected as gamepad 2, the tv remote is always the gamepad 1. We need a way to change this inside the settings menu.

Only 2 player games that can be started from a second gamepad will work.

**Comment by lukittoys** [comment]
exactly! 
lemuroid recognizes the "si-mouse" as control 1. I also have an ipega 9076, it and my dualshock 4 are recognized as the second control.

**Comment by zutmkr** [comment]
The same issue here. Philips PUS8102, detects remote as bluetooth controller. Please fix.

**Comment by glaucopgomes** [comment]
Same issue here with JVC LT-58MB708, the first gamepad detected is "MStar Smart TV IR Receiver".

**Comment by Swordfish90** [comment]
Hi guys. I tried to be as smart as possible when filtering gamepads, but sadly I don't think that's possible. I was even able to reproduce the same gamepad reported differently on different devices.

In the next release, I'll add a switch to manually disable each connected device so hopefully, all your problems will be solved.

@glaucopgomes there is a list, but it's hardcoded inside the application, so not something that you can edit without recompiling it.

**Comment by zutmkr** [comment]
To be ohnest. I think the best way to implement this is just to show the list of avaiable gamepads in config and allow user to assign gamepad to player X. That would fix any related problem.

**Comment by zutmkr** [comment]
@Swordfish90 
Some feedback regarding this feature.

1. When I disable the gamepad the assign button list should not be shown because I need to scroll down all the way to second gamepad.
2. In the PlayStation games R2 does not work. I checked diffrent games but same result.

Apart from those two issues feature works as intendent and I can play with no problem on my android tv. Good work!
