### ISSUE TITLE
Please add the DraStic core for NDS.

### ISSUE THREAD

**Issue by Dougzen** [Swordfish90/Lemuroid#221]
Hello, first of all, congratulations for the job, it's really a GOAT system.

I wanted the DraStic core for NDS because with this core, is possible play games in the less powerful smartphones.

Thank you.

**Comment by Swordfish90** [comment]
Hi @Dougzen . Thanks. I'm very glad you're enjoying Lemuroid. Drastic is indeed very nice, but sadly it's closed source, so there is no way to integrate it into Libretro or Lemuroid.

When (or if) its source code will be released I'll gladly include it, for the moment MelonDS with its dynamic recompiler will do.
