### ISSUE TITLE
Update 1.10.0 now fails too with psp games 

### ISSUE THREAD

**Issue by HJMBgit84** [Swordfish90/Lemuroid#226]
Hi Dev I just want to inform that in version 1.9.0 the PSX games game Roms did not load and now with the recent update neither the psp, the message says preparing game and crashes for both platforms in Android, please take a look if possible on that issue because now it is affecting psp games too :(

**Comment by Swordfish90** [comment]
Hi @HJMBgit84 . Could you provide a bit more context on the issue? Which device and android version are you using? How much free space do you have on your device, and have you tried clearing caches or refactoring Lemuroid do factory settings?

**Comment by HJMBgit84** [comment]
Yes, I read the message the app shows recommending to disable autosave feature and also clear cache and reset to lemuroid factory state, non of them worked unfortunately, device Poco F2 Pro running Android 11 stable, not custom rom.

**Comment by Dougzen** [comment]
Same problem here.

**Comment by Swordfish90** [comment]
Apparently it was an update in the upstream ppsspp assets as the core version was exactly the same. It has been fixed now: https://github.com/Swordfish90/Lemuroid/issues/243

**Comment by HJMBgit84** [comment]
Thank you Filippo, so I suppose that in the next update release psp games will be playable again, right? :)

**Comment by Swordfish90** [comment]
@HJMBgit84 That's correct. :)

**Comment by HJMBgit84** [comment]
Awesome!, thanks :)
