### ISSUE TITLE
Fails to build on F-Droid

### ISSUE THREAD

**Issue by jspricke** [Swordfish90/Lemuroid#232]
Hi, the latest version (1.10.0) fails to build on F-Droid:
```
Task 'assembleFreeRelease' not found in project ':lemuroid-app'.
```
https://monitor.f-droid.org/builds/log/com.swordfish.lemuroid/141

Could you help us fix this? Thanks!

**Comment by Swordfish90** [comment]
Hi @jspricke . Yeah, we probably need to update the build file on f-droid. There is a new flavour so the correct name now is: "assembleFreeDynamicRelease".

If we update the file [here](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.swordfish.lemuroid.yml) for version 1.10, would it propagate also to the next tags?

**Comment by jspricke** [comment]
I guess this should fix this: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8822/diffs#2a1f1b53fca81f9555ff9ed96a7680a1c6601cf2_78_77

> If we update the file [here](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.swordfish.lemuroid.yml) for version 1.10, would it propagate also to the next tags?

yes, it will be copied over automatically.

**Comment by Swordfish90** [comment]
@jspricke Yes, definitely looks good. Thank you for the fix!
