### ISSUE TITLE
Problem using lemuroid on huawei P40

### ISSUE THREAD

**Issue by Josstoxx** [Swordfish90/Lemuroid#233]
My name is Edwin, a long time ago I used version 1.9.0 of lemuroid on my huawei P40, however when updating to the latest version (1.10.0) it does not allow me to load any games because I do not download any core and it remains in the core update. I guess it has to do with something from the MSG. But hopefully and at some point you can add the application in the appgalery and use the HMS
Thank's

**Comment by Swordfish90** [comment]
Hi @Josstoxx . I'm glad you're enjoying Lemuroid. Which version have you been using on your P40? If you try the "free" version (free as in no Google dependencies) it should correctly fetch cores from Github.

You can find the apk here: https://github.com/Swordfish90/Lemuroid/releases/download/1.10.0/lemuroid-app-free-dynamic-release.apk

Another solution might be getting it via f-droid, which will be updated to 1.10.0 in the next 1/2 days.

Regarding publishing to AppGallery, I don't really like the process that requires me to provide bank documents and my passport: https://developer.huawei.com/consumer/en/doc/help/identityverfication-0000001053292680

**Comment by Josstoxx** [comment]
I appreciate your comment, indeed with this version if I can execute. Thank you.

And I understand about appgalery, I did not know that it asked for sensitive information

Thank you very much for answering
