### ISSUE TITLE
PSP crashes.

### ISSUE THREAD

**Issue by belmontebruno** [Swordfish90/Lemuroid#243]
Some of us (r/EmulationOnAndroid) are having constant crashes on psp games startup. Just notifying you as others said it worked before last update.

Thank you very much. Your app is amazing. I'll certainly donate to you. Would love an option to subscribe as well and support on a monthly basis.

**Comment by Swordfish90** [comment]
Hi @belmontebruno . I'm really glad you're enjoying Lemuroid and thank you for the support.

I just took a look at it and I was able to reproduce it when installing Lemuroid from scratch. It looks like the ppsspp guys updated the assets files, so a new install gathers files that are not compatible with the core version.

I'll commit a fix tonight and I'll push an update in the next few days.

If you wish to contribute with recurring donations you can do so via Patreon or PayPal using the Sponsor button here on github.
