### ISSUE TITLE
How do I make Ds games run better

### ISSUE THREAD

**Issue by danielius200629** [Swordfish90/Lemuroid#259]
When i play a ds game the fps is very bad and the sound is awful just like if you play a ds game on a browser

**Comment by OilSubjectLoss7** [comment]
Use drastic

**Comment by danielius200629** [comment]
im not paying for a different emulator, i want to use lemuroid

**Comment by OilSubjectLoss7** [comment]
> im not paying for a different emulator, i want to use lemuroid

Then suffer for laggy ds experience unless you have more powerful hardware, Drastic is the only choice right now

**Comment by danielius200629** [comment]
Fine ill just download it on aptoide tv
