### ISSUE TITLE
Remove "exit game without saving" from long press menu

### ISSUE THREAD

**Issue by mchaptel** [Swordfish90/Lemuroid#26]
This option has cost me to lose all saves twice now. Since the long press menu appears easily by mistake (pressing next to the button for example) it's easy to misclick and lose all progress.

Since the reset option exists, there is no real reason for this option to exist as users should always have the option to go back to their previous intentional save.

Maybe the long press menu should be rethought as it comes up to easily when using the touchscreen. A top bar that appears when pressing back with a menu option as well as quick saves and exit is standard and works well.

**Comment by Swordfish90** [comment]
Hi, I just merged the new implementation for save states. The long click contextual menu has been replaced by a gear touch button. I also removed the "Close without saving" entry since it's no longer useful.
