### ISSUE TITLE
Option to bind swipes

### ISSUE THREAD

**Issue by Rult** [Swordfish90/Lemuroid#261]
Useful for minimal design scenarios like rhythm games where you should press buttons blindly.

The direction of swipe on each side would correspond with one of the 4 buttons, and a point tap would correspond to L/R.

Also in this case you would need to hide the controller layout at all.

**Comment by Rult** [comment]
Not actually useful, closing this

**Comment by K9-guardian** [comment]
This would be useful for sokoban games. Baba is You on android implements swipe movement and it works quite well. It works by swiping initially which direction you want to move, and then holding down to continuously press the button. I think this is a worthwhile control option - I'll try to look into seeing how this could be implemented.

**Comment by K9-guardian** [comment]
I think I'll skip this for now actually. The low profile "snap on" controller market seems to be getting more traction now with things like the 8bit do flip which basically solves the issue of not having physical buttons entirely. This is probably a better option overall than creating a whole control scheme that's only useful for puzzle games and jrpgs.
