### ISSUE TITLE
Touch controls broken on 1080x2340 phone

### ISSUE THREAD

**Issue by simon-grimm** [Swordfish90/Lemuroid#265]
The touch controls are behaving in a very weird way on my galaxy a50. Unfortunately its unplayable this way, but i hope this video clarifies the issue enough so it can be fixed in the future.

[demo video](https://youtu.be/14klO44zzZc)

**Comment by momovideo** [comment]
It is a known issue with Samsung phones. Here is a workaround: https://github.com/Swordfish90/Lemuroid/issues/178#issuecomment-785145153

**Comment by simon-grimm** [comment]
Thank you for the quick reply, this workaround fixes it for me!
