### ISSUE TITLE
[Request] Submit to F-Droid

### ISSUE THREAD

**Issue by ghost** [Swordfish90/Lemuroid#3]
Due to the app not needing any external dependencies like RetroArch does via it's core updater, please do submit to https://f-droid.org/ for review.

**Comment by Swordfish90** [comment]
> The software should not download additional executable binary files (e.g. non-free addons, auto-updates, etc).

It's actually using libretro cores downloaded from https://buildbot.libretro.com/. These _so_ files are sadly against the f-droid policy.

**Comment by AnthonyAJumelles** [comment]
That's only an issue if they're being pulled externally after installing the app. The cores are packaged with Lemurdroid so there shouldn't be an issue.

**Comment by Swordfish90** [comment]
Apparently this might still be possible by flagging anti-features: https://f-droid.org/en/docs/Anti-Features/
