### ISSUE TITLE
I Miss your Lemuroid updates :(

### ISSUE THREAD

**Issue by HJMBgit84** [Swordfish90/Lemuroid#301]
Great project but no updates since May makes me think and ask if you are Ok?, Hope you are just busy these days.

**Comment by david79111** [comment]
> Great project but no updates since May makes me think and ask if you are Ok?, Hope you are just busy these days.

Devolepment is ongoing so please close your issue to clean up issues tab.

**Comment by HJMBgit84** [comment]
Ok I will, thanks for continuing this awesome emulator platform, if you could improve the touchscreen buttons that will be great I mean with the ability to move triggers buttons freely so I can use gaming triggers :), thanks a lot.

**Comment by HJMBgit84** [comment]
Done, thanks for all :)
