### ISSUE TITLE
Label on-screen buttons

### ISSUE THREAD

**Issue by borg286** [Swordfish90/Lemuroid#32]
Please label the on-screen buttons. The start/stop/R/L buttons are unlabeled to me on N64.

**Comment by Amnesia1000** [comment]
In NDS the buttons overlap with the touch screen and it becomes difficult to use it.

**Comment by Amnesia1000** [comment]
Answering the question you ask me on Google play, I think one way to fix it is as the Drastic developers have done, allowing to move and resize the screens and buttons. I am not a developer so I don't know if what I am saying is easy or difficult, but it is a way, if not, only allowing resizing or moving the buttons, allowing one to create their own setting

**Comment by Swordfish90** [comment]
Labels on virtual keys came with this commit: c5b8bf13eb78e944c850f7042fdd6e2680a576d6 . There is also a fix for virtual keys on ds display: right now touch and screen sizes are adjusted to prevent this from happening.
