### ISSUE TITLE
Android TV should also setup and configure a physical pads

### ISSUE THREAD

**Issue by aguaviva** [Swordfish90/Lemuroid#334]
That way people can use usb controllers/keyboards :)

Is this line disabling the physical pads?

https://github.com/Swordfish90/Lemuroid/blob/807b4b3e36310f6abc6cb3e583bb3feb6238c57c/lemuroid-app/src/main/java/com/swordfish/lemuroid/app/tv/game/TVGameActivity.kt#L20

I'd be awesome if physical pads could be used :)

Thanks again for the MOST awesome emulator and setting the bar for everyone else :)

**Comment by Swordfish90** [comment]
Hi @aguaviva . I just implemented keyboard support with #341
