### ISSUE TITLE
InputDevice.SOURCE_GAMEPAD == InputDevice.SOURCE_GAMEPAD

### ISSUE THREAD

**Issue by aguaviva** [Swordfish90/Lemuroid#336]
This line down below might meant to do something else:

https://github.com/Swordfish90/Lemuroid/blob/ebeafe6a7f3825267d5efaf401b64d4b2be26108/lemuroid-app/src/main/java/com/swordfish/lemuroid/app/shared/settings/GamePadManager.kt#L163

Cheers

**Comment by Swordfish90** [comment]
Hi @aguaviva . The line is correct :smile:
