### ISSUE TITLE
controls not working on tall displays.

### ISSUE THREAD

**Issue by plainoldcheese** [Swordfish90/Lemuroid#339]
The controls are not aligned with their graphics for tall displays. My phone has a 20:9 aspect ratio and the controls trigger when I tap above the graphic for the buttons. This is not fixed by adjusting the control positions or by playing in horizontal mode.

**Comment by fernbacher** [comment]
I have the same issues, the only method i found to bypass it sort of is to hold the right/left side of the screen when you want to press on the opposite side. Its really annoying, i love the emulator but its unusable without a controller on 20:9 aspect ratio.

**Comment by ethark** [comment]
I've also encountered this on a samsung galaxy A50 (1080x2340)

**Comment by ethark** [comment]
Hmm, I'm unable to reproduce the bug using an up-to-date debug build on android 12 with a Pixel 4a (which has the same 1080x2340 resolution). It may be already fixed. Would you like me to produce an APK for you to test?

**Comment by cdeex** [comment]
Same issue on Samsung A40 (1080 x 2340) - Android 11
I can test the APK

**Comment by ethark** [comment]
@cdeex here is an apk built against the android 11 SDK: https://litter.catbox.moe/j57tar.apk. or you can just install android studio, git clone --recursive and compile it yourself. But this one works in my aformentioned samsung galaxy A50

**Comment by Swordfish90** [comment]
Hi guys. The problem here is not resolution or aspect ratio. There is a bug in Samsung Game Mode which reports wrong coordinates when multitouch is involved. Here you can find the duplicate issue with some workaround: https://github.com/Swordfish90/Lemuroid/issues/178
