### ISSUE TITLE
Actually fully customizable buttons

### ISSUE THREAD

**Issue by Ahmedmksd** [Swordfish90/Lemuroid#347]
It says that you can move the buttons,but shit's a lie you can only make them bigger and move them a bit, and only god knows how many times i accidentally pressed settings because of how i hold my phone, maybe actually make them movable?

**Comment by mayconv7** [comment]
Hello,
I understand your situation, but the buttons are really movable and remember they are not detachable.

Lemuroid uses RadialGamePad, which is an external dependency, so I believe you have to open an Issue in the RadialGamePad repository.

**Comment by Ahmedmksd** [comment]
> Hello, I understand your situation, but the buttons are really movable and remember they are not detachable.
> 
> Lemuroid uses RadialGamePad, which is an external dependency, so I believe you have to open an Issue in the RadialGamePad repository.

Ahhhh my bad,i had no idea

**Comment by Ahmedmksd** [comment]
> > Hello, I understand your situation, but the buttons are really movable and remember they are not detachable.
> > Lemuroid uses RadialGamePad, which is an external dependency, so I believe you have to open an Issue in the RadialGamePad repository.
> 
> Ahhhh my bad,i had no idea

Well shit it was updated 11 days ago while lemuroid is like 5-8 months

**Comment by mayconv7** [comment]
Hello,
You have to consider that the Maintainer of Lemuroid has a personal and professional life to take care of.

He explained on his blog that he's been pretty busy lately, but he's slowly getting back on track.

I'm trying to answer some possible Issues that involve simple problems, to save the maintainer time.

**Comment by mayconv7** [comment]
And about updates, don't worry because the next update will be very interesting.

**Comment by Ahmedmksd** [comment]
> And about updates, don't worry because the next update will be very interesting.

Well shit i was ok waiting but now I'm hyped

**Comment by mayconv7** [comment]
Hello,
If I have resolved your Issue, please consider closing it.

And I'm also excited for the next update, now we just have to be patient and wait.
