### ISSUE TITLE
Additional Supported System(s)?

### ISSUE THREAD

**Issue by ja7833** [Swordfish90/Lemuroid#363]
The ability to play [Intellivision](https://en.wikipedia.org/wiki/Intellivision) and [ColecoVision](https://en.wikipedia.org/wiki/ColecoVision) games with Lemuroid would be welcomed.

**Comment by mayconv7** [comment]
Hello,
Why don't you put your idea in the "Ideas" category in the Discussions tab?

This keeps the Issues tab cleaner, making it easier for the Maintainer to know about Lemuroid issues.
