### ISSUE TITLE
Games don't work in the debug version

### ISSUE THREAD

**Issue by PhantomBull** [Swordfish90/Lemuroid#376]
I cloned the repository, checked out the 1.12.1 release (which should be the one available on Google Play) and I built it myself and installed it in my phone. Then I tried running a few GBC games that work in the Google Play version using the debug version of the APK, but none of them work. It just displays a spinner and neither the back button nor the menu button work.

How can I make it work?

**Comment by Swordfish90** [comment]
Hi. Did you clone the repository with --recursive to retrieve submodules? Also which variant are you trying to build? The "bundle" variants include cores in the apk, while the "dynamic" variants download them on-demand.

I'd suggest you to stick to the freeDynamicDebug variant if you're just trying to take a tour.

**Comment by PhantomBull** [comment]
Yes, I did clone with the --recursive flag.

I was trying to use the freeBundleDebug, which is the one Android Studio was taking as default. The freeDynamicDebug works as expected. Thanks ;-)
