### ISSUE TITLE
QUEST 2

### ISSUE THREAD

**Issue by IXALU** [Swordfish90/Lemuroid#379]
Correcto funcionamiento.
Como configurar el mando ????

**Comment by mayconv7** [comment]
Hello,
Could it be more descriptive? so it will be easy to help you :)

**Comment by mayconv7** [comment]
Hello,
I believe it's the information passed from the joystick that is different from the default, maybe it's a reading error? I do not know ...

this question I can't answer, but it will likely be seen by the maintainer of Lemuroid.
