### ISSUE TITLE
Screen shaking

### ISSUE THREAD

**Issue by Gabkip** [Swordfish90/Lemuroid#396]
**Describe the bug**
Screen wildly shakes whenever I play a DS game using the DeSmuMe core, game runs normally whenever I switch to MelonDS but I have all my game's save file with the DeSmuMe core and I don't wanna have to start over on all of my games.

This only happened after I updated the app and I never had any trouble like this before.

**To Reproduce**
1. Select DeSmuMe as the core for DS games
2. Click on any game
4. Screen rapidly shakes

**Expected behavior**
I expected the screen to be normal like it was before the update

**Smartphone**
 - Device: Galaxy Note20 5G
 - OS: Android12
 - Browser: App
 - Version: 1.13.0
 

https://user-images.githubusercontent.com/101735041/158676247-b8f6fb36-e082-4f6f-9793-d4149222311f.mp4

**Comment by Gabkip** [comment]
Update: Just found out that the issue was caused by the frame skip! My frame skip was set to 1 but after being set to 0, the screen doesnt shake anymore!

Still though, i hope that the frame skip gets fixed soon

**Comment by Swordfish90** [comment]
Thank you very much for the detailed report! Fixed, will be available in the next release.
