### ISSUE TITLE
3DS Games are stuck loading, possibly caused by my device's architecture?

### ISSUE THREAD

**Issue by Albnu14** [Swordfish90/Lemuroid#407]
**Describe the bug**
Lemuroid recognises .3ds files, but when opening them it tries to load the game, and gets stuck loading for a long time untill i close the app

**To Reproduce**
1. Open 3ds game
2. A loading circle appears
3. It stays like this for a long time
4. Close the app

**Expected behavior**
Game should load and start

**Smartphone (please complete the following information):**
 - Device: Samsung A02
 - OS: Android 11
 - Browser : Firefox
 - Version 98.2

**Additional context**
Since the app loads the 3ds roms for other people, the problem can only be in my device, the only thing i can think of is my device arch which is (armeabi v7a), and looking at the citra core, i can only see support for arm64
Is there any plan to add armeabi v7a and the other archs support?

I don't know what other things could cause this.

**Comment by souranild** [comment]
I have the same issue on my Realme 7 pro (Android 12, arm-64v8a)

**Comment by Swordfish90** [comment]
Sadly 3DS do not work on 32bit device. It's a limitation by Citra. There is a fix in 1.14.0 for the infinite loading.
