### ISSUE TITLE
Add a "Start" button for running Playstation 1 games.

### ISSUE THREAD

**Issue by Nishat14904** [Swordfish90/Lemuroid#464]
So I tried to play Diablo (PS-1) today. Game loaded perfectly with sounds and I was very happy with it. Suddenly after the intro finished, it said-

"Press start to play the game"

And I couldn't find any "start" button there. 
Since the game loaded fine, there's no issue from my side. 

So, adding a "start" button for this specific case would help everyone  a lot. 

Please try to fix it if possible. 🙂

*That play button doesn't work as the start button and I tried every possible button combo.

**Comment by Swordfish90** [comment]
It's already there.
