### ISSUE TITLE
These emulators are better

### ISSUE THREAD

**Issue by AngelofMe** [Swordfish90/Lemuroid#478]
I'm using RetroArch
I know their advantages

handy Atari - Lynx
load games without lynxboot.img
more options

mesen Nintendo - Nintendo Entertainment System|Nintendo - Family Computer Disk System
the most accurate NES emulator according to currently established NES test ROM suites
https://tasvideos.org/EmulatorResources/NESAccuracyTests
better hypershot light gun experience
more control options

snes9x Nintendo - Super Nintendo Entertainment System|Nintendo - Sufami Turbo|Nintendo - Satellaview
support more RA cheat codes
3 systems

mgba Game Boy|Nintendo - Game Boy Color|Nintendo - Game Boy Advance
support RA cheat codes
load games what gambatte doesn't support (such as GB/Pocket Camera)
more MBC(mappers)
3 systems

melonds Nintendo - Nintendo DS|Nintendo - Nintendo DS (Download Play)|Nintendo - Nintendo DSi|Nintendo - Nintendo DSi Decrypted|Nintendo - Nintendo DSi (Digital)
DSi games

mednafen_supergrafx NEC - PC Engine SuperGrafx|NEC - PC Engine - TurboGrafx 16|NEC - PC Engine CD - TurboGrafx-CD
SGX games
support RA cheat codes

race SNK - Neo Geo Pocket|SNK - Neo Geo Pocket Color
more options
better performance
https://youtu.be/zCYQidYQSRo

**Comment by OkyDooky** [comment]
Sorry to necro, but did any of these suggestions get implemented? Just wondering why you closed it, since these sound good and well-sourced.
