### ISSUE TITLE
ROMS it emulates

### ISSUE THREAD

**Issue by CR1MS0N24** [Swordfish90/Lemuroid#497]
Does it emulate neo Geo games because I see the finalburn neo there and looked it up on what it emulates and have tried running kof 97 on it placed in the directory chosen but it doesn't pop up on the consoles list or the discover list

**Comment by FrenchPrick** [comment]
I noticed that lemuroid can only play arcade games if they are put in the data folder

**Comment by FrenchPrick** [comment]
Also you need the neogeo bios it should go in the same folder as the games you're trying to emulate.

**Comment by CR1MS0N24** [comment]
Thanks I'll try that

**Comment by CR1MS0N24** [comment]
Ok so I did that and I'm not sure but it's scanning the directory and shows 2 of the same game

**Comment by FrenchPrick** [comment]
What did you put in the folder?

**Comment by FrenchPrick** [comment]
Also did you make sure to zip your games.

**Comment by CR1MS0N24** [comment]
Basically had the app scan the roms Directory in its data folder and with each game it just made 2 copies appear there is still one file but it makes 2

**Comment by CR1MS0N24** [comment]
So I have to zip each game does this include any for the PSP ,PS1 GBA and any games that I should put into the directory

**Comment by FrenchPrick** [comment]
What no you can put the other games in the directory you specified in the
beginning, the only games that you need to put in the data folder are your
arcade games and yes they need to be zipped and you need the neogeo bios (
just search Google for neogeo.zip).

**Comment by FrenchPrick** [comment]
Also don't use lemuroid for PSP you better off using PPSSPP.

**Comment by CR1MS0N24** [comment]
Oh 😂 my bad ye I'll do that

**Comment by FrenchPrick** [comment]
So what happened did you succeed at getting the game to play.

**Comment by FrenchPrick** [comment]
So what happened did you succeed at getting the game to play.

**Comment by CR1MS0N24** [comment]
Oh um not really I followed all the instructions but no dice

**Comment by CR1MS0N24** [comment]
I'll just use retroarch for that

**Comment by CR1MS0N24** [comment]
Most from vimms lair and coolroms

**Comment by edilberto507h** [comment]
If i try to run NEOGEO roms with lemuroid, it shows a screen, listing the files that are in the neogeo.zip as missing, but the zip is also in the same folder as the roms.

**Comment by FrenchPrick** [comment]
You see that your problem there, you need to get the roms and bios that are
made for final burn neo, you can find them on r/Roms subreddit just check
the megathread. also stop using coolroms it's not safe.

**Comment by CR1MS0N24** [comment]
oh thanks wait so just to clarify can i still use vimms lair or is that a no go

**Comment by FrenchPrick** [comment]
Yeah vimm is good for everything that isn't arcade games.

**Comment by CR1MS0N24** [comment]
aight

**Comment by CR1MS0N24** [comment]
it has been 5 months no success with any of the roms im at my wits end can someone just make a video or something that shows how to do this because clearly nothing that ive done works

**Comment by CR1MS0N24** [comment]
incase anyone does say tho that i didnt put any bios into a directory ive done that

**Comment by nireus1997** [comment]
> 以防有人说我没有把任何 bios 放入目录中，我已经这样做了

hi,  I encountered the same problem, did you solve it? tks

**Comment by CR1MS0N24** [comment]
> > 以防有人说我没有把任何 bios 放入目录中，我已经这样做了
> 
> hi,  I encountered the same problem, did you solve it? tks


Hi I just cleared the data of the app each time it refused to work or a fresh install, which somehow made it work.

NB!!Backup your saves just incase.

Hope it helps
