### ISSUE TITLE
pls pls pls add retroachievement support

### ISSUE THREAD

**Issue by chocoblin** [Swordfish90/Lemuroid#554]
i really love lemuroid but am unable to log my achievements because no support. i dont want to play on retroarch.
pls add this feature asap. it would mean a lot

**Comment by doidge-kyle** [comment]
Just FYI this is a duplicate of [#505](https://github.com/Swordfish90/Lemuroid/issues/505). Maybe consider showing your support for this feature over there.

**Comment by chocoblin** [comment]
> Just FYI this is a duplicate of [#505](https://github.com/Swordfish90/Lemuroid/issues/505). Maybe consider showing your support for this feature over there.

ok i'll do that. thanks for mentioning
