### ISSUE TITLE
Multi-touch broken in landscape mode after android 13 update 

### ISSUE THREAD

**Issue by andagel** [Swordfish90/Lemuroid#558]
**Disclamer**
Tried on RetroArch (quick test), but it does not seem to happen there. Found online description on similar issue (multi-touch offset), but specifically on Samsung phones, and behavior seems different here. Cannot apply same fix.

**Describe the bug**
After updating Google Pixel 4a to Android 13, the second touch after pressing an on-screen button defaults to the top-most button on the other keypad. E.g. left+(anywhere on screen)=triangle (or B in game boy roms); square+(anywhere on screen)=up arrow.
Does NOT occur in portrait (but happens in both landscape orientations).

**To Reproduce**
1. Start game
2. Landscape mode
3. Hold any button in one of the keypads
4. Press anywhere on the screen while holding first button.

**Expected behavior**
Well, second tap should correspond to actual location, not to something else.

**Screenshots**
![Screenshot_20220925-104150.png](https://user-images.githubusercontent.com/67195425/192135244-9173decc-730f-4bc0-9d10-8004c3a41cb4.png)

![Screenshot_20220925-104121.png](https://user-images.githubusercontent.com/67195425/192135257-c02176e9-72de-4bbe-b49b-9ab96cffa48b.png)

![Screenshot_20220925-104111.png](https://user-images.githubusercontent.com/67195425/192135276-974f0b0d-2c73-49aa-8641-6a274e1bb7f0.png)

![Screenshot_20220925-104046.png](https://user-images.githubusercontent.com/67195425/192135286-74c70557-edfc-47ae-b56c-29b6567fe25e.png)

https://user-images.githubusercontent.com/67195425/192135783-d51b08d9-8f48-4f5b-a1ba-c655f037584f.mp4

https://user-images.githubusercontent.com/67195425/192135790-15e15fb4-179e-4b1e-9e3c-af09470dc114.mp4

**Desktop (please complete the following information):**
 -N.A.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 13
 
**Additional context**
-N.A.

**Comment by joeysaladino** [comment]
Having this exact same issue on a Pixel 7 running Android 13. It does not happen on my Galaxy S21 running Android 12.

**Comment by misclicj** [comment]
Same here on Pixel 4a with Android 13.

**Comment by Git08hb** [comment]
Same here

Pixel 6
Android 13

Lemuroid from F-Droid ver: 1.14.2

**Comment by ProgrammAbel** [comment]
Same problem on Pixel 7 Pro, Android 13.

**Comment by sotfheif** [comment]
Same problem appeared on Galaxy S20 FE after upgrading to android 13.

**Comment by sthierry** [comment]
The same issue is mentionned here : https://github.com/Swordfish90/Lemuroid/issues/553
and here : https://github.com/Swordfish90/Lemuroid/issues/582

**Comment by andagel** [comment]
Fixed by dev in version 1.14.0. Well done, thanks!

**Comment by powerofpickle** [comment]
> Fixed by dev in version 1.14.0. Well done, thanks!

Weird, it's not fixed for me in 1.14.4

**Comment by pjsoftcoUser** [comment]
> Fixed by dev in version 1.14.0. Well done, thanks!

Could you please describe how you fixed it? Same is happening on my app, and cannot find the solution!

**Comment by b2yq** [comment]
I am searching a reason why multitouch is not working correctly in Android 13, could you point the commit with the fix?

**Comment by Riven781** [comment]
Did you find reason/solution?

**Comment by b2yq** [comment]
I found the reason: https://issuetracker.google.com/issues/249340921?pli=1 google made a bug and getRawX and getRawY on second and next fingers is simply returning wrong values, out of the scale :) and it will update  it in Android 15! I will never made any business with Google services
