### ISSUE TITLE
Libretro cores not loading 

### ISSUE THREAD

**Issue by zachleolewis** [Swordfish90/Lemuroid#561]
**To Reproduce**
3. Scroll 
When I open any game on any platform I get an error saying the Libretro core didn't load. No matter what I do nothing will fix it. I have reinstalled, reset to factory setting, everything. Screen shot attached.
**Smartphone (please complete the following information):**
 - Device: Samsung zFold 3
 - OS: Android 12, One UI 4.1
 - Browser: Microsoft Edge
 - Version 105
![Screenshot_20220928-011409_Lemuroid](https://user-images.githubusercontent.com/107536456/192702629-1976155d-ab6c-4ce3-ba72-6678d88c36ac.jpg)

**Comment by zachleolewis** [comment]
I don't see any notifications when scanning the directory.

**Comment by L00R33NZ00** [comment]
I had the same problem, I answered by going to settings, save to cloud, synchronize statuses and selecting the core that interested me
![IMG_20220929_152934_727](https://user-images.githubusercontent.com/99860158/193045179-4847a00c-8d7f-449e-bfe4-7b8e62a8db97.jpg)
![IMG_20220929_152936_577](https://user-images.githubusercontent.com/99860158/193045186-db13e7ed-683b-4ea7-a3d9-2790377edc81.jpg)

**Comment by StrawhatOwnen** [comment]
Hi I am getting the EXACT same problem on the exact same phone hope we can get a fix for this soon. TY for the hard work

**Comment by MarAvFe** [comment]
I had this same issue with an NDS rom.

I had an interesting behavior where the rom loaded, I left the app for a minute and when I tried to open the rom again, it raised the error, discarding the suggested reason that the core fails to load on my device.

I solved it by going to settings and selecting MelonDS instead of DesMuMe emulator. However, I think the real solution was to manually close the emulator: Close the app, go to rom, and hold to option of "Restart".

**Comment by Swordfish90** [comment]
I've been able to reproduce the issue and pushed a tentative fix. I'm publishing today another release in beta, let me know if this fixed the issue for you.

**Comment by Swordfish90** [comment]
Nope. Issue is sadly still there. Will keep working on it.

**Comment by Swordfish90** [comment]
Fix has now been released in beta. Cores are downloaded from Google Play so we can't have complete control over what happens, but this solution is more robust and the error message contains possible workarounds.
