### ISSUE TITLE
Support for custom Gamepad layouts

### ISSUE THREAD

**Issue by Tossis** [Swordfish90/Lemuroid#57]
Right now gamepads are supported, but on my 8BitDo SN30Pro the A and X buttons are swapped with the B and Y button. If we could re-bind the keys, or select a different layout that would be perfect.

**Comment by Swordfish90** [comment]
I just merged #58 which handles exactly this :)

**Comment by Tossis** [comment]
Great :) Tempted to clone and compile me a preview now. Can't wait for the release.

**Comment by Swordfish90** [comment]
I just published the changes in beta, so you probably won't need to build it from source :)
