### ISSUE TITLE
Lemuroid on Android 13

### ISSUE THREAD

**Issue by LucasGGamerM** [Swordfish90/Lemuroid#582]
**Disclamer**
In order to keep this bug tracker manageable, you need to keep a few things in mind.
* Any issue not following this template will be closed as invalid
* Is the issue reproducible on RetroArch with the same core? If so, it's very likely a core issue and the upstream core repository is a better place to file it
* Is the issue already opened? Try out a search before filing one.

**Describe the bug**
Landscape controls are broken under android 13, and selecting a folder that is on the root of the system (/storage/emulated/0/) makes it that lemuroid can't read the rom files. Putting my ROMs directory on the documents folder works as expected 

**To Reproduce**
Open any game on lemuroid on android 13, turn it to landscape, and try to press both the action buttons and directional joystick at the same time. The result is a completely unplayable game. As for the second one, just select any directory on the root of the device. It previously worked under android 12 and below.  

**Expected behavior**
Normal control experience, ie: being able to use the joystick and action buttons at the same time. And for the second one, it shouldn't matter if the directory is under root.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google pixel 3
 - OS: CalyxOS android 13 (AOSP)

**Comment by LucasGGamerM** [comment]
And that's a recording of the bug

**Comment by incelloprocci** [comment]
having the same problem since updating to Android 13

**Comment by sthierry** [comment]
I am having the exact same issue on my Samsung Galaxy A32 5G since last update.
I am now on Android 13, One UI 5.0.
Core version :
4.14.186.25331340

It worked perfectly fine before.
I hope you'll be able to solve the issue, Lemuroid is the best android emulator out there.

**Comment by sthierry** [comment]
The same issue is mentionned here : https://github.com/Swordfish90/Lemuroid/issues/558
and here : https://github.com/Swordfish90/Lemuroid/issues/583

**Comment by sthierry** [comment]
It now work perfectly fine again since last Lemuroid update. Thanks a lot !

**Comment by Senkudou** [comment]
I'm also having this issue. I'm on a Pixel 7 Pro on Android 13 (specifically using GrapheneOS). It seems to work fine in portrait but in landscape it doesn't work at all:
![screen-20230215-072552_3_AdobeExpress](https://user-images.githubusercontent.com/125425183/218920777-d0469142-e3bd-453e-8041-2780706e2d49.gif)

**Comment by nikhilCad** [comment]
Close the issue
