### ISSUE TITLE
F-Droid and APK releases are out of date

### ISSUE THREAD

**Issue by IAGOnDiscord** [Swordfish90/Lemuroid#608]
Title says all. The most recent release version I can find (1.14.4) is only available on the Google Play Store. On the other hand, version 1.14.2 is the most recent available release as an APK here on Github and for F-Droid. Presumably this has something to do with a GSF dependency somewhere. Others have mentioned this (see #603) but no issue has explicitly been filed.

I and others would like to see an updated release for F-Droid and/or as an APK. Releasing a standalone APK here on Github would also clarify that releases have been made since 1.14.2 (which was released four months ago!) and that the project is still active.

Retroarch is an alternative with inferior default settings and looks, but improved customization and no GSF dependencies that I can see. If it's impossible to release a version of Lemuroid for F-Droid or as an APK, I'll continue to use Retroarch.

**Comment by HatoGreyrat** [comment]
I have the same opinion :(

**Comment by barfin** [comment]
Yes, not all devices have google play store, and installing an apk from apps and websites like aurorastore simply isn't possible because google play version of lemuroid uses google play store to download and update cores unlike and this can't be done without having play store on that device

**Comment by Git08hb** [comment]
Same problem here

**Comment by dylanwatsonsoftware** [comment]
Looks like its now been released since the latest available on Google Play store is now 1.15.0.
This should be closed.

**Comment by IAGOnDiscord** [comment]
Weird, I thought this was closed already. There's still no release on F-Droid but there is an APK. As long as the Play Store isn't the only way to download it...

**Comment by AminurAlam** [comment]
so f-droid won't be getting any future updates?

**Comment by IAGOnDiscord** [comment]
F-Droid release is out! Sixteen days ago, actually.

**Comment by qaqland** [comment]
I think we need one edtion with all cores included in apk
