### ISSUE TITLE
Simultaneous face button presses don't work

### ISSUE THREAD

**Issue by drxt** [Swordfish90/Lemuroid#61]
The current touch controls are well implemented but they lack the ability to independently being able to be pressed simultaneously. Actions such as holding the A button and mashing B don't work, as holding one button seems to disable the rest until you let go. This makes playing games that have slow scrolling text very annoying (such as many RPGs), and precision platformers and fighting games that require you to combo multiple buttons at the same time.

**Comment by Swordfish90** [comment]
I agree. The current behaviour of "sticky" keys doesn't work very well in certain cases. I'll try to come up with a fix.

**Comment by Swordfish90** [comment]
This landed with version 1.5.0. Multi-touch events are now behaving as you expect.
