### ISSUE TITLE
Lemuroid outside the Play Store is outdated

### ISSUE THREAD

**Issue by HatoGreyrat** [Swordfish90/Lemuroid#610]
There is no updated version for android users who don't have Play Store. F-droid and Github versions are not in their latest version compared with Play Store's. Aurora Store version does not allow you to download the cores, and APKs on webpages like Uptodown or Apkpure have outdated cores and don't allow you to update them.

**Comment by ericsomto** [comment]
You could just use play store like everybody does

**Comment by HatoGreyrat** [comment]
My device does not have Play Store and using Gspace does not allow me to scan roms.

**Comment by HatoGreyrat** [comment]
My device does not have Play Store and using Gspace it does not allow me to scan roms.

**Comment by barfin** [comment]
> You could just use play store like everybody does

No, That's not a solution, not everybody have or want google play store

**Comment by IAGOnDiscord** [comment]
Seconded. I filed a very similar issue (#608) a few days ago.
