### ISSUE TITLE
GBA emulator doesn't support zipped ROMS

### ISSUE THREAD

**Issue by HFPasfho** [Swordfish90/Lemuroid#647]
**Describe the bug**
GBA emulator doesn't support zipped ROMS. Other emulators I tested works with zipped ROMS.

**To Reproduce**
1. Zip a ROM
2. Refresh library in settings
3. Game disappears from games list

**Expected behavior**
GBA emulator should support zipped ROMS as other emulator does.

**Smartphone (please complete the following information):**
 - Device: S9
 - OS: Android 10
 - Version Lemuroid 1.15

**Comment by manero6** [comment]
I'm able to play zipped roms, in fact all GBA games I play are zipped.
I'm talking about `.zip`, not sure about `.7z`.

**Comment by HFPasfho** [comment]
Yes I can confirm it's true. I tried 3 different android file managers and the zips they created weren't working. That's why I created this issue. After @manero6's reply I tried zipping my roms on PC and they seem to work just fine which is strange. I close this issue because it turned out it was file managers not Lemuroid fault.
