### ISSUE TITLE
Slow performances on MiBox

### ISSUE THREAD

**Issue by Swordfish90** [Swordfish90/Lemuroid#65]
It seems after a few tries that Lemuroid runs slowly on a MiBox, we should profile it to understand how we can improve it.

See #51 for more details.

**Comment by rodrigoswz** [comment]
Apparently fixed after I updated the Mi Box to Android 9.

But unfortunately something in the latest beta version of Lemuroid does not accept the buttons of my bluetooth joystick (ipega 9025) so I can't play to test it.

**Comment by Swordfish90** [comment]
Hi @rodrigoswz . That's actually great news! Would be interesting to investigate how they fixed it but I'm happy anyway. Is the gamepad detected in Lemuroid? Are you able to navigate the UI and change key bindings?

**Comment by rodrigoswz** [comment]
Yes, I can do all of that, only when I open a game on Lemuroid that my gamepad does not respond. It happens on my phone too btw, it is not something exclusive in Mi Box this time.

**Comment by Swordfish90** [comment]
Ok. What I changed in one of the last update (which fixed some missing touch control issues) is trusting android entirely on the matter. When a device is connected, if android recognizes it as a gamepad it gets a portNumber > 0, otherwise 0.

https://developer.android.com/reference/android/view/InputDevice#getControllerNumber()

Could you please check with Logcat if you're able to see an error, or if the gamepad gets assigned 0?

If that's the case, I guess we should have an advanced option to manually force or disable gamepad detection (it's not the solution I like most, but we have cases of fingerprint readers recognized as gamepads, and gamepads not recognized as gamepads, so I don't think there is any other solution).

**Comment by Swordfish90** [comment]
@rodrigoswz . I might have a fix for the gamepad not working. I've added more details as #62 and I'm going to publish it to beta in the next days. Right now I'm closing this, if you have any feedback you can use the other issue.
