### ISSUE TITLE
Add option to rotate screen based on sensor

### ISSUE THREAD

**Issue by manero6** [Swordfish90/Lemuroid#654]
It would be great to have an option to bypass the android rotation setting and have the screen to rotate based on the sensor.

I think having the following option will cover all different cases:

Screen orientation:
- follow android setting
- portrait
- landscape
- based on sensor

I hardly change my android screen orientation, I normally have it locked, but I change it everytime I use Lemuroid.

**Comment by manero6** [comment]
I noticed that in Android 12+ there is a shortcut to manually rotate the screen even when "auto-rotation" is deactivated.

This works very well with lemuroid. One simply needs to tilt the screen and then press the rotation shortcut that appears.

![lemuroid rotate](https://github.com/Swordfish90/Lemuroid/assets/21221315/280d89bc-17d4-4cd1-8eab-13f26c3a5ab3)

A dedicated setting would be nice, but this actually work quite fine already.  
The issue is closed for me.

**Comment by ffoxD** [comment]
I feel like having to manually rotate the screen via the OS' options every single time is a very cheap workaround. even with Android 12's indicator (that works very inconsistently, is very annoying and is not meant to be used like this), I still think this is a very serious usability issue.
