### ISSUE TITLE
On MiBox storage permission dialog is not prompted

### ISSUE THREAD

**Issue by Swordfish90** [Swordfish90/Lemuroid#66]
The storage permission dialog is not shown when starting the application on a MiBox. I'm not able to reproduce the issue on the emulator or my FireStick 4k so we need to investigate this a bit more.

See #51 for more details.

**Comment by rodrigoswz** [comment]
Fixed in the latest version of Lemuroid + Android 9 update released recently 🎉

**Comment by Swordfish90** [comment]
Again, great news! I guess it safe to close this issue now.
