### ISSUE TITLE
[Proposal] Add Github workflow for releasing

### ISSUE THREAD

**Issue by mcatta** [Swordfish90/Lemuroid#687]
### Context
I see that each release is tagged and the APK is attached to the GitHub release, but I don't see any automation for this flow, I suppose it's manual.

### Proposal
Given that there are some Github actions on the market like https://github.com/marketplace/actions/automatic-releases I would propose a new workflow with these parameters:

#### Trigger
- pushed tags
```
on:
  push:
    tags:
      - "*"
```
#### Operations
- Build an APK by using `./gradlew assembleRelease`
- Upload the APK as artefact
- Create a release (in pre-release) by using https://github.com/marketplace/actions/automatic-releases
  - This will include all new commit messages inside the changelog
  - The generated APK stored as artefact

### Requirements
Given that the script will build the APK with `buildType: release` we should persist the keystore and password inside the Github secrets, we can use [GPG to increase the security](https://stefma.medium.com/how-to-store-a-android-keystore-safely-on-github-actions-f0cef9413784).

### Extra
If needed we could run the test suits before the build if needed.

I did it for my personal projects, I can take ownership of the task.

**Comment by Swordfish90** [comment]
Hi @mcatta . What a pleasure seeing you here! 😄 ... That's something I've been wanting to do for a very long time so feel free to take it, and thank you very much for your help!

As you guessed, currently all builds are handmade, and for each tag on the release branch (which is basically master with the crowdin translations merged in).

Currently the playstore version is not published on github, and I think it should still be the case so let's just keep here the de-googled variants:

`./gradlew assembleFreeRelease`

**Comment by mcatta** [comment]
The PR is ready: https://github.com/Swordfish90/Lemuroid/pull/689 there are a couple of action items

**Comment by mcatta** [comment]
I close the issue given that PR is merged
