### ISSUE TITLE
Bios are not detected/used on Android 13

### ISSUE THREAD

**Issue by newhinton** [Swordfish90/Lemuroid#693]
**Describe the bug**
When storing a bios inside the selected rom-folder, it wont be shown as detected. If i manually copy those files into internal storage, they show up. In neither case the bios is actually used, and libretro-core reports that no bios files were found.

**To Reproduce**
1. Set up Emulator with Android 13
2. Store a game and a corresponding bios on the sd card
3. Set up lemuroid
4. Start game and watch logs

**Expected behavior**
Lemuroid copies the bios files from the rom-folder to internal storage and then uses them.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Pixel 7/Emulator
 - OS: GrapheneOS 13/Android13

**Additional context**
I tested both the current f-droid version, and a debug build.

Edit:
I forgot to mention that i use a custom bios-file that is known to work with other emulators. Its the ps3 one.

**Comment by newhinton** [comment]
Okay, i figured out why: the core expects the firmware-files to start with `scph` so they have to be named properly.

**Comment by catguy323** [comment]
I'm on a galaxy a15 and I have the same bug and I don't know what you mean by naming it properly
