### ISSUE TITLE
Request and feadback

### ISSUE THREAD

**Issue by juanreina921** [Swordfish90/Lemuroid#70]
Hello Swordfish, I am a blind user of lemuroidd, and I have a small request of you. In future updates of Lemuroidd, could it be possyble to keep this interface? This interface is most accessible to us, especially because retroarch is no longer acessible on Android. Could it be possyble to add an arcade core? Thanks so much, and hope you take my requests into consideration.

**Comment by Swordfish90** [comment]
Hi @juanreina921, I gladly accept t gladly accept this request. I'll try to keep the application as accessible as possible, and if I miss something feel free to report it on github and I'll fix it right away.

There is already an arcade core (FBNeo) which requires a different romset though, I'll surely add plain MAME support in one of the next versions.
