### ISSUE TITLE
Implement Accessibility in LemuroidVirtualGamepad (and RadialGamePad)

### ISSUE THREAD

**Issue by juanreina921** [Swordfish90/Lemuroid#73]
Hey it's Juan here, and I have a bit of an issue. Upon starting laytest version of lemuroid, all menus, buttons, and tabs look fine, but when I start a game, the menu for saving and loading, restart settings and quit, are no longer available to the screen reader. Additionally, I can't see the surtain controls, like start and select, l1 and l2, r1/2. I would be grateful, as I rather independent gameing, than someone accessing menus and pressing start on a game for me. Thanks in advance, Juan.

**Comment by Swordfish90** [comment]
Hi Juan. I'm sorry about that. The new touch overlay is using a custom view, so the accessibility support is not implemented by default. It doesn't look straightforward, but I'm definitely going to fix it. Thank for reporting it!

**Comment by juanreina921** [comment]
@Swordfish90, no problem. So I take it that this view was also letting the screen readers see lemuroid's game menu?

**Comment by Swordfish90** [comment]
@juanreina921 Hi Juan! Could you please send me an email to the email address you find here on github (or the one I use on Google Play)? In the next days I'm going to try implementing the accessibility in RadialGamePad and I'd like to send you a test apk to make sure everything works as expected.

**Comment by juanreina921** [comment]
Yeah. Like this?

**Comment by Swordfish90** [comment]
This was fixed in 1.5.1. Closing the issue.
