### ISSUE TITLE
Weak network, load core failed

### ISSUE THREAD

**Issue by qaqland** [Swordfish90/Lemuroid#806]
**Expected behavior**

Weak network, load core failed.

FOSS at all but "depends" on specified network's service.
It will be helpful if users could load COREs manually, just like ROMs' do.

I tried reinstall. 

**Screenshots**

![Screenshot_20230904-134431](https://github.com/Swordfish90/Lemuroid/assets/62464571/760a32de-47d4-4b7d-9650-d2811b0eb4a4)

**Smartphone (please complete the following information):**

 - Device: Retroid Pocket 2S
 - OS: Android 11
 - Version 1.15.0

**Additional context**

Google Play is not supported here. GitHub is almost not supported here too.

**Comment by DerPannseJim** [comment]
https://www.techdoctoruk.com/sdm_downloads/lemuroid-1-10/
build in kernel but still no choice. they just included
