### ISSUE TITLE
Access external drives on Android TV

### ISSUE THREAD

**Issue by SpaceFrags** [Swordfish90/Lemuroid#83]
Using the TV version of the app it let me only search for a directory for the Roms in the Internal Storage without any possibility of using External Removable Storages like USB drive or HDD connected to the USB of my MiBox. Obviously I would put my roms in a external drive cause the internal storage is not big enough.

**Comment by Swordfish90** [comment]
Agreed. This is definitely something we need to implement.

**Comment by juanreina921** [comment]
@Swordfish90, could you if it's possible, make it so that sd cards could be used with Lemuroid as well? Thanks.

**Comment by Swordfish90** [comment]
@juanreina921 Sure. Implementing this should work on any Removable Storage (as Android like to call it).

**Comment by Siushaga** [comment]
Came to GitHub looking specifically for this. Just got done setting up Lemudroid on my SHIELD and had USB loaded for content, but could only search root device storage. 

Glad to see it's identified as a feature enhancement. Copied over portions of my library with LAN transfer to try things out. Works like a charm. Excited to dive in deeper later on!
