### ISSUE TITLE
No cover for Resident Evil 2, PSX 

### ISSUE THREAD

**Issue by Gagnef03** [Swordfish90/Lemuroid#84]
I added Resident Evil 2 PS1 and it does not have a cover image, my other games do.

This is potentially not an issue, if so please let me know so I can remove it. ![Screenshot_20200827-120555.jpg](https://user-images.githubusercontent.com/46574798/91427216-dae0f580-e85d-11ea-82ad-74b9c1ccf2ff.jpg)

**Comment by Swordfish90** [comment]
Hi @Gagnef03 , sadly can happen. It looks like the ROM file is correctly matched in the database (you can see the developer), but the game doesn't have a cover on https://db.libretro.com/. I hope that with time, and community support more games will get their cover.
