### ISSUE TITLE
The Libretro core was not loaded

### ISSUE THREAD

**Issue by DeadGodRebel** [Swordfish90/Lemuroid#840]
**Disclamer**
In order to keep this bug tracker manageable, you need to keep a few things in mind:
* Any issue not following this template will be closed as invalid
* Is the issue reproducible on RetroArch with the same core? If so, it's very likely a core issue and the upstream core repository is a better place to file it
* Is the issue already opened? Try out a search before filing one.

**Describe the bug**
The libretro core is not loading. Checked all the past issues and not issue similar to mine. Just installed Lemuroid and installed some nes snd n64 roms, not rom is opening and giving me the error.

**To Reproduce**
Just open the app and run a rom.

**Expected behavior**
I expect it to run the rom.

**Screenshots**
![Screenshot_20231205_121300_Lemuroid.jpg](https://github.com/Swordfish90/Lemuroid/assets/91931562/a68f2d99-f3ea-4958-8dea-d91b38f8b70d)

**Smartphone (please complete the following information):**
 - Device: Samsung S21 FE
 - OS: ONE UI 5.1

**Additional context**

**Comment by HFPasfho** [comment]
Did you do what this message asked you to do? Looks like you disabled internet access and lemuroid can't download required core.

**Comment by HFPasfho** [comment]
Or maybe you moved/renamed roms names after scaning?

**Comment by DeadGodRebel** [comment]
No nothing like that...it was stock as it was..i am guessing it could be a cpu think as it is an exynos chip!

**Comment by DeadGodRebel** [comment]
Good news: the games are loading...just checked!

Bad news: did not change any settings and left it as it is! So dont know what issue was.

**Comment by HFPasfho** [comment]
I remember it happened to me once too. Killing the app resolved the issue so I didn't bother to report it.

**Comment by DeadGodRebel** [comment]
Same problem for ds games now..... waited 2 days to report it...😅

**Comment by HFPasfho** [comment]
@DeadGodRebel Try to force close app, clear app cache and start it again (with wifi enabled) or restart the whole phone if this didn't help

**Comment by DeadGodRebel** [comment]
@HFPasfho no use did eveything, i think there is an issue with my ohone where cores are not loading!

**Comment by tangshxiao** [comment]
![微信图片_20240606232248](https://github.com/Swordfish90/Lemuroid/assets/20818651/834332fc-f84b-4507-8850-13da593e1e57)
The problem still exists, has it been resolved?

**Comment by xuanhieu147** [comment]
Has anyone solved this problem? I try to build apk from source code and get the above error, but when I download the app from Google Play Store it works fine?
