### ISSUE TITLE
Support for dual joy-con

### ISSUE THREAD

**Issue by Trumbuca** [Swordfish90/Lemuroid#846]
The app is great, clean and functional, everything I wanted.

But I would like do use my nintendo switch joy-cons to play, both of them as one controller.
Right now, for an input, I can only choose the input of one device, the Right joycon or Left joycon.
I'd like to be able to turn on the input of both devices for the RetroPad Port 1

It will make my phone a perfect retro handheld combined with this gadget 
https://www.aliexpress.com/item/1005006059883948.html?spm=a2g0o.order_detail.order_detail_item.4.2d4632e3A4vVJr

Thanks in advance!

**Comment by david79111** [comment]
This issue is already open so please close it #394
