### ISSUE TITLE
[3DS] Option to install .CIA title updates and DLCs

### ISSUE THREAD

**Issue by nesper8** [Swordfish90/Lemuroid#867]
**Issue**
Many 3DS games often have post launch DLCs and updates which are in the .CIA (CTR Importable Archive) format. Lemuroid at the moment does not have the option to install these .CIA updates and DLCs making many of these game contents and/or bugfixes inaccessible at the moment

**Solution**
Have a small updates and dlc manager for the Citra core which you can later install these comments later into

Thank you

**Comment by zaisty** [comment]
+1 Yes that is needed.

**Comment by david79111** [comment]
already mentioned in #402 so please close your issue
