### ISSUE TITLE
[Request] Customizable internal resolution

### ISSUE THREAD

**Issue by lijamez** [Swordfish90/Lemuroid#87]
One of the most important settings for me is increasing the internal resolution (2x, 3x, 4x, etc) to improve image quality, especially for PSX, N64, and PSP.

**Comment by Swordfish90** [comment]
It is now possible to increase the resolution on cores that support it (N64 and PSP). Sadly the PSX core Lemuroid is using (pcsx_rearmed) doesn't have that feature.
