### ISSUE TITLE
[Request] Replace PicoDrive with Genesis Plus GX in Genesis/MD

### ISSUE THREAD

**Issue by ghost** [Swordfish90/Lemuroid#9]
This would allow for SG-1000, Master System, and Game Gear support. Already available as a LibRetro core.

**Comment by AnthonyAJumelles** [comment]
I think I have a handle on how Lemuroid handles cores so I submitted the change of PicoDrive to Genesis Plus GX and added Master System support.  Lemme know if I missed anything of import!

**Comment by AnthonyAJumelles** [comment]
See #11

**Comment by Swordfish90** [comment]
IMHO this are two separate issues. 
We can add support for another system (such as the SMS) without changing core for the MD, and we can change core for MD without adding another system.
I'm open to replacing PicoDrive with Genesis Plus GX for MD if there is a good reason without involving other consoles.

**Comment by KarmicBacklash** [comment]
Genesis Plus GX is generally considered the more accurate and feature complete emulator. Where as Picodrive is best suited for underpowered systems that are just looking to emulate at full speed without regard to accuracy. Most phones in the modern day are powerful enough that the increased accuracy wont hurt performance. We only gain from having the accuracy of Genesis Plus GX and only loose the enhanced features the core provides over picodrive.

**Comment by Swordfish90** [comment]
I agree with you. But it's better to keep the issues separate.

**Comment by Swordfish90** [comment]
This has been done in ead15a694db68b19e2d4fa6c19983944105921ae.
