### ISSUE TITLE
Updating the version in Github

### ISSUE THREAD

**Issue by master1274** [Swordfish90/Lemuroid#905]
Hello developer. How soon will the build be available apk here? The update is already out on Google Play. But not everyone has Google Play.

**Comment by david79111** [comment]
yeah I agree, but I think he's already working on.
You can see it in the actions tab but I'm not 100% sure if thats related.

**Comment by master1274** [comment]
However, some time has passed. And it looks like it's not particularly important for the developer to update the version here. Google Play beat GitHub.

**Comment by david79111** [comment]
Cut him some slack. He's doing this in his free time for no money. If enough people ask for it he'll do it sooner or later.

**Comment by HatoGreyrat** [comment]
It's now available
