### ISSUE TITLE
Boxart Covers for games with & in name

### ISSUE THREAD

**Issue by Siushaga** [Swordfish90/Lemuroid#92]
https://github.com/Swordfish90/Lemuroid/blob/b61f966f313a3309c4fb63e99b917a55c2258d1e/lemuroid-metadata-libretro-db/src/main/java/com/swordfish/lemuroid/metadata/libretrodb/LibretroDBMetadataProvider.kt

Above appears to have functions for fetching boxart from Libretro Database. This has been working well, although it's unable to fetch any games with "&" symbols in their titles. Reason appears to be that the ROM name is used when deciding which png to pull from Named_Boxarts. 

While the ROM name on the Libretro Database metadata appears with a "&" in the name, the thumbnails in Named_Boxarts instead of have "_" in place of "&". 

Example ROM name:
"Adventures of Batman & Robin, The (USA)"

Example of Named_Boxarts thumbnail:
"Adventures of Batman _ Robin, The (USA)"

Couple of example games from https://db.libretro.com...
Game Metadata:
https://db.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Adventures%20of%20Batman%20_%20Robin,%20The%20(USA).html
Named_Boxarts Thumbnail:
http://thumbnails.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Named_Boxarts/Adventures%20of%20Batman%20_%20Robin,%20The%20(USA).png

Game Metadata:
https://db.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Joe%20_%20Mac%20(USA).html
Named_Boxarts Thumbnail:
http://thumbnails.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Named_Boxarts/Joe%20_%20Mac%20(USA).png

**Comment by Swordfish90** [comment]
Nice catch. I guess those characters are not escaped correctly.

**Comment by Swordfish90** [comment]
Thank you again for reporting this. I fixed it.

Just a note, you should perform full rescan (first scan an empty directory and then rescan your ROMs directory) to see the effect. That's because the old mistaken urls have to be purged from the database.
