### ISSUE TITLE
File picker doesn't show

### ISSUE THREAD

**Issue by xzfantom** [Swordfish90/Lemuroid#947]
**Describe the bug**
I installed Lemuroid 1.16.1 from F-Droid to my Xiaomi Box 4K (2nd Gen) with AndroidTV 11 installed and try to open folder with games. Instead appears message: "This device does not support the StorageAccessFramework file picker..." and asks to copy files to lemuroid folder. The problem is that when I try to access this folder with external FileManager - it's not accessible even if all permissions on file access are granted.

**To Reproduce**
1. Go to Settings
2. Click on Directory
3. See message about not supported file picker (that closes by itself in second)

**Expected behavior**
File picker should allow me to choose file with game ROM

**Screenshots**
![выява](https://github.com/user-attachments/assets/6ccf763c-6774-43f9-81c2-f86a745a3e0a)

**AndroidTV (please complete the following information):**
 - Device: Xiaomi Box 4K (2nd Gen)
 - OS: AndroidTV 11
 - Browser stock
 - Version

**Additional context**
Maybe problem is not in file picker, but in access restriction for default folder

**Comment by branches78** [comment]
See https://github.com/Swordfish90/Lemuroid/issues/498 for reference on the global issue with Android 11+.

**Comment by xzfantom** [comment]
> See https://github.com/Swordfish90/Lemuroid/issues/498 for reference on the global issue with Android 11+.

Thanks! Missed it
