### ISSUE TITLE
Games have blank box art

### ISSUE THREAD

**Issue by KibSquib48** [Swordfish90/Lemuroid#976]
**Disclamer**
In order to keep this bug tracker manageable, you need to keep a few things in mind:
* Any issue not following this template will be closed as invalid
* Is the issue reproducible on RetroArch with the same core? If so, it's very likely a core issue and the upstream core repository is a better place to file it
* Is the issue already opened? Try out a search before filing one.

**Describe the bug**
Games have blank boxes instead of box art

**To Reproduce**
1. Open the app
2. The home tab has games with only titles, no art

**Expected behavior**
The box art should be loaded, I assume from some external server(?)

**Screenshots**
![Screenshot_20241210-103145](https://github.com/user-attachments/assets/c423db6c-e5c4-4585-af81-ef50573a26a2)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 15 QPR1
 - Version: 1.16.2

**Comment by KibSquib48** [comment]
Seems like it fixed itself, I guess the box art server came back up?

**Comment by duckytej** [comment]
What did u do to fix it ? I cleared cashe and after that no matter what I delete and download I am not getting the cover art back for any of the games

**Comment by b1ohazard777** [comment]
I deleted the app. I deleted everything on my device that had anything to do with the app. I then downloaded an APK of the app and installed it. On my device, the box art showed up again. I then deleted the app again. I installed it again from the app store and the box art shows up.
I hope that works for you.
